[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]
linker = "rust-lld"

[target.aarch64-unknown-none-softfloat]
rustflags = [
    "-Clink-arg=-Tsrc/linker-aarch64.ld", "-Cforce-frame-pointers=yes"
]
linker = "rust-lld"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
