//! 错误类型转换，用于将数字常量转换为BlueErr （linux）

use super::BlueErr;

impl From<i32> for BlueErr {
    /// 从正数错误码转换为 BlueErr
    fn from(code: i32) -> Self {
        match code {
            1 => BlueErr::EPERM,
            2 => BlueErr::ENOENT,
            3 => BlueErr::ESRCH,
            4 => BlueErr::EINTR,
            5 => BlueErr::EIO,
            6 => BlueErr::ENXIO,
            7 => BlueErr::E2BIG,
            8 => BlueErr::ENOEXEC,
            9 => BlueErr::EBADF,
            10 => BlueErr::ECHILD,
            11 => BlueErr::EAGAIN,
            12 => BlueErr::ENOMEM,
            13 => BlueErr::EACCES,
            14 => BlueErr::EFAULT,
            15 => BlueErr::ENOTBLK,
            16 => BlueErr::EBUSY,
            17 => BlueErr::EEXIST,
            18 => BlueErr::EXDEV,
            19 => BlueErr::ENODEV,
            20 => BlueErr::ENOTDIR,
            21 => BlueErr::EISDIR,
            22 => BlueErr::EINVAL,
            23 => BlueErr::ENFILE,
            24 => BlueErr::EMFILE,
            25 => BlueErr::ENOTTY,
            26 => BlueErr::ETXTBSY,
            27 => BlueErr::EFBIG,
            28 => BlueErr::ENOSPC,
            29 => BlueErr::ESPIPE,
            30 => BlueErr::EROFS,
            31 => BlueErr::EMLINK,
            32 => BlueErr::EPIPE,
            33 => BlueErr::EDOM,
            34 => BlueErr::ERANGE,
            35 => BlueErr::EDEADLK,
            36 => BlueErr::ENAMETOOLONG,
            37 => BlueErr::ENOLCK,
            38 => BlueErr::ENOSYS,
            39 => BlueErr::ENOTEMPTY,
            40 => BlueErr::ELOOP,
            42 => BlueErr::ENOMSG,
            43 => BlueErr::EIDRM,
            44 => BlueErr::ECHRNG,
            45 => BlueErr::EL2NSYNC,
            46 => BlueErr::EL3HLT,
            47 => BlueErr::EL3RST,
            48 => BlueErr::ELNRNG,
            49 => BlueErr::EUNATCH,
            50 => BlueErr::ENOCSI,
            51 => BlueErr::EL2HLT,
            52 => BlueErr::EBADE,
            53 => BlueErr::EBADR,
            54 => BlueErr::EXFULL,
            55 => BlueErr::ENOANO,
            56 => BlueErr::EBADRQC,
            57 => BlueErr::EBADSLT,
            59 => BlueErr::EBFONT,
            60 => BlueErr::ENOSTR,
            61 => BlueErr::ENODATA,
            62 => BlueErr::ETIME,
            63 => BlueErr::ENOSR,
            64 => BlueErr::ENONET,
            65 => BlueErr::ENOPKG,
            66 => BlueErr::EREMOTE,
            67 => BlueErr::ENOLINK,
            68 => BlueErr::EADV,
            69 => BlueErr::ESRMNT,
            70 => BlueErr::ECOMM,
            71 => BlueErr::EPROTO,
            72 => BlueErr::EMULTIHOP,
            73 => BlueErr::EDOTDOT,
            74 => BlueErr::EBADMSG,
            75 => BlueErr::EOVERFLOW,
            76 => BlueErr::ENOTUNIQ,
            77 => BlueErr::EBADFD,
            78 => BlueErr::EREMCHG,
            79 => BlueErr::ELIBACC,
            80 => BlueErr::ELIBBAD,
            81 => BlueErr::ELIBSCN,
            82 => BlueErr::ELIBMAX,
            83 => BlueErr::ELIBEXEC,
            84 => BlueErr::EILSEQ,
            85 => BlueErr::ERESTART,
            86 => BlueErr::ESTRPIPE,
            87 => BlueErr::EUSERS,
            88 => BlueErr::ENOTSOCK,
            89 => BlueErr::EDESTADDRREQ,
            90 => BlueErr::EMSGSIZE,
            91 => BlueErr::EPROTOTYPE,
            92 => BlueErr::ENOPROTOOPT,
            93 => BlueErr::EPROTONOSUPPORT,
            94 => BlueErr::ESOCKTNOSUPPORT,
            95 => BlueErr::EOPNOTSUPP,
            96 => BlueErr::EPFNOSUPPORT,
            97 => BlueErr::EAFNOSUPPORT,
            98 => BlueErr::EADDRINUSE,
            99 => BlueErr::EADDRNOTAVAIL,
            100 => BlueErr::ENETDOWN,
            101 => BlueErr::ENETUNREACH,
            102 => BlueErr::ENETRESET,
            103 => BlueErr::ECONNABORTED,
            104 => BlueErr::ECONNRESET,
            105 => BlueErr::ENOBUFS,
            106 => BlueErr::EISCONN,
            107 => BlueErr::ENOTCONN,
            108 => BlueErr::ESHUTDOWN,
            109 => BlueErr::ETOOMANYREFS,
            110 => BlueErr::ETIMEDOUT,
            111 => BlueErr::ECONNREFUSED,
            112 => BlueErr::EHOSTDOWN,
            113 => BlueErr::EHOSTUNREACH,
            114 => BlueErr::EALREADY,
            115 => BlueErr::EINPROGRESS,
            116 => BlueErr::ESTALE,
            117 => BlueErr::EUCLEAN,
            118 => BlueErr::ENOTNAM,
            119 => BlueErr::ENAVAIL,
            120 => BlueErr::EISNAM,
            121 => BlueErr::EREMOTEIO,
            122 => BlueErr::EDQUOT,
            123 => BlueErr::ENOMEDIUM,
            124 => BlueErr::EMEDIUMTYPE,
            125 => BlueErr::ECANCELED,
            126 => BlueErr::ENOKEY,
            127 => BlueErr::EKEYEXPIRED,
            128 => BlueErr::EKEYREVOKED,
            129 => BlueErr::EKEYREJECTED,
            130 => BlueErr::EOWNERDEAD,
            131 => BlueErr::ENOTRECOVERABLE,
            132 => BlueErr::ERFKILL,
            133 => BlueErr::EHWPOISON,
            _ => BlueErr::EINVAL,
        }
    }
}

/// 从 syscall 返回值提取错误或成功值
///
/// Linux syscall 约定：
/// - 成功：返回 >= 0 的值
/// - 失败：返回 -errno（负数）
pub fn from_syscall_ret(ret: isize) -> Result<usize, BlueErr> {
    if ret >= 0 {
        Ok(ret as usize)
    } else {
        Err(BlueErr::from((-ret) as i32))
    }
}


