OUTPUT_ARCH(aarch64)
ENTRY(_blue_start)

BASE_ADDRESS = 0x40080000; 
/* BASE_ADDRESS = 0x00480000; 香橙派 */ 
SECTIONS
{
    . = BASE_ADDRESS;
    skernel = .;

    stext = .;
    .text : {
        *(.text.entry)
        . = ALIGN(4K);
        straper = .;
        *(.text.traper)
        . = ALIGN(4K);
        *(.text .text.*)
    }

    . = ALIGN(4K);
    etext = .;
    srodata = .;
    .rodata : {
        *(.rodata .rodata.*)
        *(.srodata .srodata.*)
    }

    . = ALIGN(4K);
    erodata = .;
    sdata = .;
    .data : {
        *(.data.app)
        *(.data .data.*)
        *(.sdata .sdata.*)
    }

    . = ALIGN(4K);
    edata = .;
    .bss : {
        sbss = .;
        *(.bss.stack)
        estack = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
    }

    . = ALIGN(4K);
    ebss = .;
    ekernel = .;

    _kernel_size = ekernel - skernel;

    /DISCARD/ : {
        *(.eh_frame)
    }
}
