#!/usr/bin/env python3
"""Generate the BlueStarOS aggregate C test runner."""

from __future__ import annotations

import argparse
from pathlib import Path


def case_name(module: str, source: Path) -> str:
    return f"{module}/{source.stem}"


def emit_runner(cases: list[tuple[str, str]]) -> str:
    entries = "\n".join(
        f'    {{"{name}", "{path}"}},' for name, path in cases
    )
    return f"""// Generated by test/tools/gen_runner.py. Do not edit by hand.
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

struct test_case {{
    const char *name;
    const char *path;
}};

static const struct test_case TEST_CASES[] = {{
{entries}
}};

static int run_one(const struct test_case *tc) {{
    pid_t pid = fork();
    if (pid < 0) {{
        printf("[TESTOS][CASE][FAIL] %s fork_errno=%d\\n", tc->name, errno);
        return 1;
    }}
    if (pid == 0) {{
        char *const argv[] = {{(char *)tc->path, NULL}};
        char *const envp[] = {{NULL}};
        execve(tc->path, argv, envp);
        printf("[TESTOS][CASE][FAIL] %s exec_errno=%d\\n", tc->name, errno);
        _exit(127);
    }}

    int status = 0;
    pid_t waited = waitpid(pid, &status, 0);
    if (waited != pid) {{
        printf("[TESTOS][CASE][FAIL] %s wait_errno=%d\\n", tc->name, errno);
        return 1;
    }}
    if (WIFEXITED(status) && WEXITSTATUS(status) == 0) {{
        printf("[TESTOS][CASE][PASS] %s\\n", tc->name);
        return 0;
    }}
    if (WIFEXITED(status)) {{
        printf("[TESTOS][CASE][FAIL] %s code=%d\\n", tc->name, WEXITSTATUS(status));
    }} else if (WIFSIGNALED(status)) {{
        printf("[TESTOS][CASE][FAIL] %s signal=%d\\n", tc->name, WTERMSIG(status));
    }} else {{
        printf("[TESTOS][CASE][FAIL] %s status=%d\\n", tc->name, status);
    }}
    return 1;
}}

int main(void) {{
    const int total = (int)(sizeof(TEST_CASES) / sizeof(TEST_CASES[0]));
    int pass = 0;
    int fail = 0;

    printf("[TESTOS][BEGIN]\\n");
    for (int i = 0; i < total; ++i) {{
        if (run_one(&TEST_CASES[i]) == 0) {{
            ++pass;
        }} else {{
            ++fail;
        }}
    }}
    printf("[TESTOS][SUMMARY] total=%d pass=%d fail=%d\\n", total, pass, fail);
    printf("[TESTOS][END]\\n");
    return fail == 0 ? 0 : 1;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--module", required=True, help="module name, e.g. syscall")
    parser.add_argument("--output", required=True, help="generated C output path")
    parser.add_argument("sources", nargs="+", help="C test sources")
    args = parser.parse_args()

    sources = sorted(Path(src) for src in args.sources)
    cases = [
        (case_name(args.module, src), f"/test/{args.module}/{src.stem}")
        for src in sources
    ]
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_runner(cases), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
